### ISSUE TITLE
Do you want me to add GitHub Actions?

### ISSUE THREAD

**Issue by KTibow** [TekniskSupport/home-assistant-resrobot#12]
If you want, I can contribute some advanced CI to your repository in a PR. Let me know if you want that.

**Comment by TekniskSupport** [comment]
Doesn't tell me much, what does it do? But please do, and I'll look at it I suppose?
I'ts a rather simple integration, nothing advanced or special really. Just polls a few values off of a rest api

**Comment by KTibow** [comment]
- I can add some flake8. It catches invalid Python code.
- I can also add some auto-formatting. Would you like that?
- It can be packaged or independent. I recommend packaged because it keeps on getting updates. Which one do you want?

**Comment by KTibow** [comment]
Sorry, accidentally closed.

**Comment by TekniskSupport** [comment]
Not sure what you (or I am) are gaining from this
this is a really simple one-file integration repository.

I usually do most validation and linting before committing, unless it's a publishing pipeline or a many-developer repository

**Comment by KTibow** [comment]
Got it. BTW you should try installing `wemake-python-styleguide` locally, it's very strict but it can help you improve your code a lot.
