### ISSUE TITLE
ResRobot found no trips

### ISSUE THREAD

**Issue by Skaveny** [TekniskSupport/home-assistant-resrobot#13]
Kan du förklara vad jag har gjort fel? Jag skickar med 2 bilder ena med error och en bild på min config och en bild som visar hur det ser ut på min lovelace

![image](https://user-images.githubusercontent.com/1252745/104330247-19660c80-54ee-11eb-8f7c-09a1055ed299.jpeg)

![image](https://user-images.githubusercontent.com/1252745/104330273-1ff48400-54ee-11eb-92fc-e9a62539d6d3.jpeg)

![image](https://user-images.githubusercontent.com/1252745/104330301-2420a180-54ee-11eb-9ac9-522ac5d777d2.jpeg)

**Comment by TekniskSupport** [comment]
Hej,

Det är inte du som har gjort fel, det är jag.
Det ligger en issue någonstans i bakhuvudet att jag skall fixa det felet.

Såhär går det till, datakällan har begränsat antal requests per månad, det är anledningen till att man måste registrera sig osv

Sedan vill man ofta ha en sensor för trafik åt ena hållet och en sensor med trafik åt andra hållet, kanske ytterligare för fler linjer mm.

För undvika att slå i taket i antalet förfrågningar gör jag en stor förfrågan per konfiguration, lagrar undan den i "helper"-entieteten, och bygger de övriga sensorerna utifrån den datan

Precis när du startar home assistant har inte hjälpsensorn fått någon data ännu och linjerna har inga resor, en minut senare när sensorerna uppdateras nästa gång så dyker trafiken upp, 

Det är med andra ord jag som loggar ett fel, även om allt egentligen står rätt till

vänligen Iesus

**Comment by TekniskSupport** [comment]
Har nu tagit bort de onödiga meddelandena.
