### ISSUE TITLE
Feature request - Show result as hh:mm only instead of hh:mm:ss

### ISSUE THREAD

**Issue by QueensGamb** [TekniskSupport/home-assistant-resrobot#14]

**Comment by TekniskSupport** [comment]
Hi,

I've been reluctant to change the data coming from the API , but i will consider it.
Would be easy enough to do with a template sensor thou.

**Comment by TekniskSupport** [comment]
Added time_format to configuration,
use as in https://man7.org/linux/man-pages/man3/strptime.3.html
