### ISSUE TITLE
remove unused import

### ISSUE THREAD

**Issue by fredamn76** [TekniskSupport/home-assistant-resrobot#15]
This import has changed in Home Assistant, and with block the integration from starting on > 2021.3.0.
Since it was not used, it need to be removed in this PR.

For more information look att https://github.com/Lallassu/smhialert/pull/7

**Comment by TekniskSupport** [comment]
This would break the integration, the depencency you removed is the one used to collect and update data.

**Comment by TekniskSupport** [comment]
Solved by changing the import instead, the restData was only moved up one step in heirarcy
