### ISSUE TITLE
Error beta 0.13

### ISSUE THREAD

**Issue by fredamn76** [TekniskSupport/home-assistant-resrobot#19]
Home Assistant: core-2022.2.6
Beta 0.13 does only get value for sensor 0.
No error in logs

**Comment by TekniskSupport** [comment]
![image](https://user-images.githubusercontent.com/13868526/153723875-895f411f-a100-4f92-a22e-6de4f532593e.png)

I seem to get more than one sensor populated, but there also seems to be an issue there, as i only get my first four sensors with data

**Comment by TekniskSupport** [comment]
Should have been resolved with .14, .15
