### ISSUE TITLE
Unable to find Bus 1 from Malmö C towards Kristianstad

### ISSUE THREAD

**Issue by radicalcurtain** [TekniskSupport/home-assistant-resrobot#23]
Hello!

Thank you for a great tool. I used it successfully in my old apartment to track buses from Malmö to Lund with no issues. However, now I try to track SkåneExpressen buss 1 from Malmö C towards Kristianstad. And I think I've tried everything but I haven't been able to find the times yet (tried line 001, tried a different stop_id etc). I don't know if it's caused by a special type of buss (e.g. it's skåneexpressen - I'm not sure that is a factor) or what it might be.

Any tips are welcome!

Thank you in advance,

sensor bussarna:
- platform: resrobot
key: mysecretapikey
fetch_interval: 1440
departures:                            
- stop_id: 740000003                   # Look in the stops.txt file
name: Buss 1
max_journeys: 100                     # Number of departures to fetch
sensors: 6                          # Number of sensors to create
unit: "🕑"                           # unit_of_measurement
time_format: "%H:%M"                 # Do not fetch from NOW but now+n minutes, also consider the departed n minutes before it actually departs, e.g. time it takes you to walk to the bus)
filter:
- line: 1
type: contains
direction: kristianstad

**Comment by TekniskSupport** [comment]
My best guess is that the line number is not 1 in the response from the integration, I've come across this before when there are express buses and other "special" routes

I would consider removing the filter and searching for the route in the json-helper entity to double check if it's there

**Comment by radicalcurtain** [comment]
Thank you, this worked! The name of the line was SkX 1. Not 1 :).
